# Source: srsran-5g/templates/du-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysrsran-srsran-5g-du
  namespace: "ran"
  labels:
    app.kubernetes.io/name: srsran-5g-du
    app.kubernetes.io/instance: mysrsran
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: srsran-5g-du
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: srsran-5g-du
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
            { "name": "fronthaul-network", "interface": "fh", "ips": [ "192.168.40.3/24" ] },
            { "name": "midhaul-network", "interface": "f1", "ips": [ "10.10.5.2/24" ] }
            ]'
    spec:
      containers:
        - name: mysrsran-srsran-5g
          image: forad/srsran5g:24_10
          imagePullPolicy: 
          command:
            - srsdu
          args:
            - -c
            - /tmp/du.yml
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
            privileged: true
          envFrom:
          ports:
            - name: gtpu
              containerPort: 2152
              protocol: UDP
          volumeMounts:
            - name: du-config
              mountPath: /tmp/du.yml
              subPath: du-template.yml
            - name: gnb-config
              mountPath: /tmp/gnb.yml
              subPath: gnb-template.yml
      volumes:
        - name: du-config
          configMap:
            name: mysrsran-srsran-5g-cu-du-configs
        - name: gnb-config
          configMap:
            name: mysrsran-srsran-5g-cu-du-configs
