apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: fronthaul-network
  namespace: ran
  annotations:
    k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/n4br
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ovs",
      "bridge": "fronthaul-br",
      "mtu": 9000,
      "ipam": {
        "type": "static"
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: midhaul-network
  namespace: ran
  annotations:
    k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/n4br
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ovs",
      "bridge": "f1-br",
      "mtu": 1450,
      "ipam": {
        "type": "static"
      }
    }'
